import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    // _id will be automatically generated by MongoDB as ObjectId
    name: { 
        type: String, 
        // required: true // Let's make this optional initially
    },
    email: { 
        type: String, 
        required: true, 
        unique: true, // Ensure emails are unique
        lowercase: true, // Store emails in lowercase
        trim: true // Remove whitespace
    },
    imageUrl: { 
        type: String 
        // required: true // Let's make this optional initially
    },
    // Add any other fields you need, like role, etc.
    // role: { type: String, enum: ['student', 'educator', 'admin'], default: 'student' }, 
    enrolledCourses: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Course'
        }
    ],
}, { timestamps: true });

// Index the email field for faster queries
userSchema.index({ email: 1 });

const User = mongoose.model("User", userSchema);

export default User